---
- name: create 'certs' folder
  file:
    path: /etc/nginx/certs
    state: directory

- name: copy ssl certeficate
  template:
    src: certeficates/test2022-frontend-rostyslav-m.abzdev2.com.cer
    dest: /etc/nginx/certs/test2022-frontend-rostyslav-m.abzdev2.com.cer
    owner: root
    group: root
    mode: '0644'

- name: copy ssl key
  template:
    src: certeficates/test2022-frontend-rostyslav-m.abzdev2.com.key
    dest: /etc/nginx/certs/test2022-frontend-rostyslav-m.abzdev2.com.key
    owner: root
    group: root
    mode: '0644'